### ISSUE TITLE
Only titles are exported

### ISSUE THREAD

**Issue by waaldiigam** [DjLeChuck/foundryvtt-babele-translation-files-generator#1]
When exporting compendiums with items and their descriptions, "Babele translation files generator" is exporting only titles.

This is how file is looking, when I am using babele to export:
![image](https://github.com/DjLeChuck/foundryvtt-babele-translation-files-generator/assets/55682846/0a66067c-e1f2-4138-90d3-4b4f20a6fbe8)
And this is how it looks when I used tool (babele was turned off before export)
![image](https://github.com/DjLeChuck/foundryvtt-babele-translation-files-generator/assets/55682846/80c221d0-7462-4daf-bb5b-86d9b17a12f5)
As you can see, a lot is missing. Is there any way to use this tool to export all items properties? Or for this purpose I should use babele instead?

**Comment by DjLeChuck** [comment]
Hi,

That's the default behaviour. If you want to export other data in your file, you must use the mapping feature in order to map a system field with a JSON field.

For example, if your description is in `system.description.value`, you muste set this in the first field of mapping and for example `description` in the second. After that, your file will contains the `name` and the `description` for each items.

**Comment by waaldiigam** [comment]
Thanks, any possibility that you will add some more user friendly feature in future? I don't know how problematic it would be to gather all possibilities onto a list with checkboxes for users to export. But it is just an idea.

**Comment by DjLeChuck** [comment]
@waaldiigam I don't think it's possible. Each system is different and some have dozens of fields, some not needed for translation, some nested on many levels...
Be able to "guess" what field is translatable is not possible.
I know this mapping part is tricky, especially if you are not used to data management in Foundry. :/

However, I'm open for any suggestions to improve the interface! Just, don't expect things to be too automatic unfortunately.
